Repository Anikesh02/Eldcare, pull requests merged in 2024-10, with the labels that each got.

#14 Feature darkmode
  src/App.css
  src/components/Faq/FaqItem.jsx
  src/components/Header/Header.jsx
  src/components/Hospitals/HospitalCard.jsx
  src/components/Services/ServiceCard.jsx
  src/index.css
  src/pages/Contact.jsx
  src/pages/Home.jsx
  src/pages/Hospitals/Hospitals.jsx
  src/pages/Login.jsx
  tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#16 [fix : #15] profile button not working
  package-lock.json
  package.json
  src/components/Header/Header.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 sign up ui fix
  src/pages/Hospitals/Appointment.jsx
  src/pages/Signup.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#26 Added Subscription Model
  src/components/Subscription/PricingCard.css
  src/components/Subscription/PricingCard.jsx
Labels: enhancement, good first issue

#28 Added Functionality for Searching Nearby Hospitals
  src/pages/Hospitals/Hospitals.jsx
Labels: enhancement

#33 Bug fixed of visibiity in dark mode
  src/components/Caretaker/CareTaker.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
